export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const PAGINATED_TODO = "PAGINATED_TODO"
export const PAGINETED_TO_NEXT_PAGE = "PAGINETED_TO_NEXT_PAGE"